In [21]:
import numpy as np

In [22]:
# sigmoid function
def actf(x):
    return 1/(1+np.exp(-x))
# first derivative of sigmoid

def actf_deriv(x):
    return x*(1-x)

# input node, hidden node, output node
inputs, hiddens, outputs = 2, 2, 1
learning_rate=0.2

# training samples and it labels
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
T = np.array([[0], [1], [1], [0]])

In [23]:
W1 = np.array([[0.10,0.20], [0.30,0.40]])
W2 = np.array([[0.50],[0.60]])
B1 = np.array([0.1, 0.2])
B2 = np.array([0.3])

In [24]:
# forward propagation
def predict(x):
    layer0 = x # feed in the input to the input layer
    Z1 = np.dot(layer0, W1)+B1 # matrix multiplication
    layer1 = actf(Z1) # activation function
    Z2 = np.dot(layer1, W2)+B2 # matrix multiplication
    layer2 = actf(Z2) # activation function
    return layer0, layer1, layer2

In [25]:
# Back propagation calculation
def fit():
    global W1, W2, B1, B2 # Need to update variable outside of this function
    for i in range(90000): # iterate for 90000 times
        for x, y in zip(X, T): # for each training sample
            x = np.reshape(x, (1, -1)) # reshape to 2-dimensional matrix ①
            y = np.reshape(y, (1, -1)) # reshape to 2-dimensional matrix
            
            layer0, layer1, layer2 = predict(x) # forward compute
            layer2_error = layer2-y # error
            layer2_delta = layer2_error*actf_deriv(layer2) # delta of output layer
            layer1_error = np.dot(layer2_delta, W2.T) # error of hidden layer ②
            layer1_delta = layer1_error*actf_deriv(layer1) # delta of hidden layer ③

            W2 += -learning_rate*np.dot(layer1.T, layer2_delta) # ④
            W1 += -learning_rate*np.dot(layer0.T, layer1_delta) #
            B2 += -learning_rate*np.sum(layer2_delta, axis=0) # ⑤
            B1 += -learning_rate*np.sum(layer1_delta, axis=0) # 

In [26]:
def test():
    for x, y in zip(X, T): # for each sample
        x = np.reshape(x, (1, -1)) # reshape to 2 dimensional matrix
        layer0, layer1, layer2 = predict(x)
        print(x, y, layer2) # print output

In [27]:
fit()
test()

[[0 0]] [0] [[0.00814407]]
[[0 1]] [1] [[0.99154105]]
[[1 0]] [1] [[0.99152258]]
[[1 1]] [0] [[0.01038517]]


### 2-layer DNN for XOR

In [28]:
def fit():
    global W1, W2, B1, B2
    for i in range(60000):
        layer0, layer1, layer2 = predict(X)

        layer2_error = layer2-T
        layer2_delta = layer2_error*actf_deriv(layer2)
        layer1_error = np.dot(layer2_delta, W2.T)
        layer1_delta = layer1_error*actf_deriv(layer1)

        W2 += -learning_rate*np.dot(layer1.T, layer2_delta)/4.0
        W1 += -learning_rate*np.dot(layer0.T, layer1_delta)/4.0
        B2 += -learning_rate*np.sum(layer2_delta, axis=0)/4.0
        B1 += -learning_rate*np.sum(layer1_delta, axis=0)/4.0

def test():
    for x, y in zip(X, T):
        x = np.reshape(x, (1, -1)) # reshape to 2 dimensional matrix
        layer0, layer1, layer2 = predict(x)
        print(x, y, layer2)
        
fit()
test()

[[0 0]] [0] [[0.00746125]]
[[0 1]] [1] [[0.99226229]]
[[1 0]] [1] [[0.99224618]]
[[1 1]] [0] [[0.00949302]]
