In [6]:
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

In [7]:
import tensorflow as tf
import sklearn

2024-03-18 15:05:26.588737: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [8]:
print(tf.__version__)
print(sklearn.__version__)

2.10.0
1.0.2


## Python Basic

In [18]:
# variable
r = 20
PI = 3.14
area = PI * r**2
area

1256.0

In [20]:
# list
lst = [10, 20, 30, 40, 50]
print(lst)
print(lst[2])
print(len(lst))

[10, 20, 30, 40, 50]
30
5


In [21]:
# list slicing
print(lst[0:3]) # 0 ~ 2
print(lst[2:]) # 2 ~ end
print(lst[:-1]) # 0 ~ end-1

[10, 20, 30]
[30, 40, 50]
[10, 20, 30, 40]


In [22]:
# Dictionary
car = {'HP' : 200, 'make' : "BNW"}
print(car['HP'])
car['color'] = "white"
print(car)

200
{'HP': 200, 'make': 'BNW', 'color': 'white'}


In [23]:
# if-else
temp = -10
if temp < 0:
    print('below zero')
else:
    print('above zero')

below zero


In [26]:
# for loop
for i in [1, 2, 3, 4,5]:
    print(i, end=' ')

1 2 3 4 5 

In [29]:
# function
def sayHello(name):
    print('Hello, ' + name)

sayHello("Kim")

Hello, Kim


In [31]:
# class
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def sayHello(self):
        print("Hello, 나의 이름은", self.name)

p1 = Person("John", 36)
p1.sayHello()

Hello, 나의 이름은 John


## Numpy

In [11]:
import numpy as np

In [12]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [13]:
a[0]

1

#### Array Operations

In [14]:
# Addition
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[1, 1], [1, 1], [1, 1]])
result = arr1 + arr2
result

array([[2, 3],
       [4, 5],
       [6, 7]])

In [15]:
# Multiplication : scalar * array
miles = np.array([1, 2, 3])
result = miles * 1.6
result

array([1.6, 3.2, 4.8])

In [16]:
# Multiplication : same-shaped arrays
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[2, 2], [2, 2], [2, 2]])
result = arr1 * arr2
result

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

#### Functions

## Matplotlib