In [5]:
# 이론값과 랜덤데이터를 시뮬레이팅한 결과를 비교
# 시뮬레이션 모듈 구현 시 일반화할 수 있게 구현할 것!! (콘스탄트를 수정 ... ) 3번;;
# 4번은 코드도 다 잇으니 구조 이용해서 확률 계산 ...

In [6]:
# Read CSV file

# pip install biogeme
# pip install pandas
# pip install numpy
# import os
from scipy.special import factorial # scipy -> 통계/데이터분석에 유용한 functions 포함된 라이브러리 
import numpy as np

### Problem 01

Suppose  there  are  **10  cars**  waiting  at  an  intersection(교차로)  in  a  single  line,  

and  **4  of  them  are  left turners**. ( 4개의 좌회전 차량 -> 6개는 우회전 차량 ) 

The vehicles are equally likely to be in any order. 

Use Python to calculate the probability that: 

In [22]:
# a. The first four vehicles are all left turners. 첫 번째 네 개의 차량이 모두 좌회전 차량
denominator = (factorial(10)/(factorial(4)*factorial(6))) # 10개의 차량 중 

numerator_a = 1 # 4C4 = 1
ans_a = numerator_a/denominator

In [23]:
# b. None of the first four vehicles are left turners. 첫 번째 네 개의 차량이 모두 좌회전 차량이 아님
numerator_b = (factorial(6)/(factorial(4)*factorial(2))) # 6C4
ans_b = numerator_b/denominator

In [10]:
# c. No non-left-turning vehicle has more than two left turners in front of it.
# 우회전 차량 앞에 2개 초과?의 좌회전 차량 X
# from math import comb -> I use Python 3.7.x so used scipy instead
from scipy.special import comb

numerator_c = comb(8,2) # 8C2
ans_c = numerator_c/denominator

In [11]:
# result
print(ans_a, ans_b, ans_c)

0.004761904761904762 0.07142857142857142 0.13333333333333333


### Problem 02
Verify your calculations in (1) using a small Python simulation.

In [13]:
# a. Create  a  vector of  10  random  numbers.  
# Imagine  1  stands  for  the  first  vehicle  in  line  at the intersection, 
# 2 stands for the 2nd vehicle, etc. 
# (Hint: Use ‘rand’ function of numpy)

veh = np.random.rand(10) # Uniform dist (0~1) 
veh

array([0.87896007, 0.84521722, 0.29502556, 0.41455242, 0.26097679,
       0.45419406, 0.62721589, 0.700294  , 0.61429265, 0.09215683])

In [14]:
# b. Use  b)  to  randomly  choose  which  of  the  10  vehicles  are  left  turners.  
# For  example  the left-turners  could  be  the  vehicles  whose  associated  random  numbers  are  the  smallest. 
# (Hint: Use ‘sort’ function of numpy) 

value = np.sort(veh)
index = np.argsort(veh)
print('value: ', value)
print('index: ', index)

leftTurners = index[0:4] # First four vehicles
leftTurners = np.sort(leftTurners)
print('Left turners: ', leftTurners)

value:  [0.09215683 0.26097679 0.29502556 0.41455242 0.45419406 0.61429265
 0.62721589 0.700294   0.84521722 0.87896007]
index:  [9 4 2 3 5 8 6 7 1 0]
Left turners:  [2 3 4 9]


In [15]:
# c. For this set of left turners, determine whether 
# each of the events identified in Problem 1 is correct, 
# record the results in three binary variables, one for each of the three events. 

# First four vehicles are left turners
# print(leftTurners[0] == 1, leftTurners[1] == 2, leftTurners[2] == 3, leftTurners[3] == 4)
print(leftTurners[3] == 4)

# Non of the first four vehicles are left turners
# print(leftTurners<=4)
print(sum(leftTurners<=4)==0)

# No non-left-turning vehicle has more than two left turners in front of it. 
print((leftTurners[3] == 9) & (leftTurners[2] == 8)) # remember range of index 

False
False
False


In [25]:
# d. Repeat the above steps 10,000 times 
# and estimate the probabilities for the three events (in Problem 1) from your results. 

import numpy as np 

# Function to locate the left turners
def locateLeftTurner(n, l):
    veh = np.random.rand(n) # Uniform dist (0~1) 
    value = np.sort(veh)
    index = np.argsort(veh)
    
    leftTurners = index[0:l] # First l vehicles
    leftTurners = np.sort(leftTurners)
    return(leftTurners)


def testABC(leftTurners, n, l):
    vtestResult = [(leftTurners[3] == 4), sum(leftTurners<=4)==0, ((leftTurners[3] == 9) & (leftTurners[2] == 8))] 
    return(vtestResult)


# n: total cars, l: left turner count, m: simulate count
def simulation(n, l, m): 
    # make 3 by 1 and 3 by m matrix -> 이론 상 추정한 값과 실제 값 비교를 위한 함수이므로 ... 
    vProbABC = np.zeros((3,1)) # dummy table 3x1
    result = np.zeros((3,m)) # dummy table 3xm

    for i in range(m-1):
        result[:,i] = testABC(locateLeftTurner(n,l), n, l)

    vProbABC[0] = sum(result[0])/m
    vProbABC[1] = sum(result[1])/m
    vProbABC[2] = sum(result[2])/m
    
    return(vProbABC)


Result = simulation(10, 4, 10000)
Result

array([[0.0181],
       [0.0251],
       [0.1391]])

### Problem 03
Revise the codes developed in 1 and 2 

so that they can handle any  number  n  of  total  vehicles  and  any  number  of  left  turners,  l,  up  to  n.  

Save  the  python function as simulation.py. 

Show solutions for ...

In [ ]:
# functions 
# Create simulation.py and save it to the same directory. 
from simulation import *

In [26]:
# a. n=15,l=6
Result_a = simulation(15, 6, 10000)
print(Result_a)

[[0.0333]
 [0.0425]
 [0.0575]]


In [29]:
# b. n=20,l=8
Result_b = simulation(20, 8, 10000)
print(Result_b)

[[0.0403]
 [0.0491]
 [0.0463]]


In [28]:
# c. n=50,l=20 
Result_c = simulation(50, 20, 10000)
print(Result_c)

[[0.0544]
 [0.068 ]
 [0.0379]]


### Problem 04
Define  the  random  variable  X  to  be  the  largest  number  of  left-turners  in  front  of  any  non-left 
turner.  

They need not be directly in front, just somewhere between the non-left-turner and the 
front.

In [21]:
# Provide your answer
import numpy as np

def calculate_X(n, l):
    """
    n: 전체 차량 수
    l: 왼쪽으로 회전하는 차량의 수
    """
    # 전체 차량의 인덱스 배열 생성
    vehicles = np.arange(n)
    # 왼쪽으로 회전하는 차량의 인덱스를 무작위로 선택
    left_turners = np.sort(np.random.choice(vehicles, l, replace=False))
    
    # 최대 왼쪽 회전 차량 수를 저장할 변수 초기화
    max_left_turners_in_front = 0
    
    # 각 비회전 차량에 대하여 앞쪽에 있는 왼쪽 회전 차량의 수 계산
    for i in vehicles:
        if i not in left_turners:
            # 해당 비회전 차량 앞쪽에 있는 왼쪽 회전 차량의 수
            num_left_turners_in_front = np.sum(left_turners < i)
            # 최대값 업데이트
            max_left_turners_in_front = max(max_left_turners_in_front, num_left_turners_in_front)
    
    return max_left_turners_in_front

# 예시 실행
n = 10  # 전체 차량 수
l = 3   # 왼쪽으로 회전하는 차량의 수
X = calculate_X(n, l)
print(f"비회전 차량 앞쪽에 있는 왼쪽 회전 차량의 최대 개수(X): {X}")

비회전 차량 앞쪽에 있는 왼쪽 회전 차량의 최대 개수(X): 3


In [33]:
# new answer
denominator = factorial(10)/(factorial(4)*factorial(6))

# X=0 -> left turner가 맨 뒤에 4개 고정, 분자 1
numerator_0 = 1
prob_0 = numerator_0 / denominator

# X=1 -> left turner 1명 고르기 6C1
numerator_1 = comb(6,1) # factorial(5)/(factorial(6))
prob_1 = numerator_1 / denominator

# X=2 -> 2명의 lt 7C2
numerator_2 = factorial(7)/(factorial(5)*factorial(2))
prob_2 = numerator_2 / denominator

# X=3 -> 8C3
numerator_3 = factorial(8)/(factorial(5)*factorial(3))
prob_3 = numerator_3 / denominator

# X=4 -> 9C4
numerator_4 = factorial(9)/(factorial(5)*factorial(4))
prob_4 = numerator_4 / denominator

print(prob_0, prob_1, prob_2, prob_3, prob_4)

0.004761904761904762 0.02857142857142857 0.1 0.26666666666666666 0.6
